---
name: Procedimientos
locale: es
type: learning
beta: false
teacher_info: ''
language: gobstones
id_format: "%05d"
order:
- 12
- 1
- 2
- 3
- 14
- 4
- 13
- 5
- 9
- 10
- 11
- 6
- 15
- 7
- 8
private: false
